title = "Passively enumerate subdomains"
description = "List subdomains based on SSL cerificates with crt.sh"
tags = ["bash", "osint", "misc", "enum"]

[[data]]
description = "Substitute <URL>:"
language = "bash"
command = """curl -s 'https://crt.sh/?q=<URL>&output=json' | jq -r ".[].name_value" | sort -u"""
