name: Convert .toml to json

on:
  push:
    branches:
      - toml

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Install Dependencies
      run: npm install toml

    - name: Run Script for Each File
      run: |
        for file in entries/*; do
          if [ -f "$file" ]; then
            node toml2json.js "$file" > /tmp/output.json
          fi
        done

    - name: Upload to S3
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2 

    - name: Upload Results to S3
      run: aws s3 cp /tmp/output.json s3://weaponize/